server:
    port: 8087
    
logging:
    level:
        com:
            thoughtfocus: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %m %n"

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/thoughtfocus
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: Bakka@1434
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
        
        
#server.port=8087

#spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#logging.level.com.thoughtfocus=DEBUG
##logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %m %n

#spring.datasource.url=jdbc:mysql://localhost:3306/thoughtfocus
#spring.datasource.username=root
#spring.datasource.password=Bakka@1434
#spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql: true